github: [devinschumacher]
open_collective: devinschumacher
custom: [
"https://apps.serp.co/patreon-downloader",
"https://extensions.serp.co/",
"https://serp.co/products/patreon-downloader/reviews/",
"https://devinschumacher.com/patreon-downloader",
]
